shootx = 12;
shooty = -1;
handx = 42;
handy = -14;
shellX = 20;
flashX = 75;
Name = "CLASSIC ASSAULT RIFLE";
_parent._parent.rof = 4;
_parent._parent.firepower = 22;
_parent._parent.recoil = 0.8;
_parent._parent.blowback = 7;
_parent._parent.bullets = 30;
_parent._parent.idlerotate = -60;
_parent._parent.adjustrof();
_parent._parent.pushback = 10;
_parent._parent.weight = 0.8;
