shootx = 7;
shooty = 0;
handx = 42;
handy = -14;
shellX = 21;
flashX = 64;
Name = "COVERT ASSAULT RIFLE";
_parent._parent.rof = 5;
_parent._parent.firepower = 22;
_parent._parent.recoil = 0.8;
_parent._parent.blowback = 7;
_parent._parent.bullets = 30;
_parent._parent.idlerotate = -70;
_parent._parent.adjustrof();
_parent._parent.pushback = 10;
_parent._parent.weight = 0.8;
