shootx = 2;
shooty = -1;
handx = 58;
handy = -11;
shellX = 20;
flashX = 55;
Name = "AVERAGE SHOTGUN";
_parent._parent.rof = 25;
_parent._parent.firepower = 7;
_parent._parent.recoil = 5;
_parent._parent.blowback = 20;
_parent._parent.bullets = 10;
_parent._parent.idlerotate = -80;
_parent._parent.adjustrof();
_parent._parent.pushback = 30;
_parent._parent.weight = 0.8;
shotgun = 7;
