shootx = 10;
shooty = 3;
handx = 42;
handy = -13;
shellX = 20;
flashX = 55;
Name = "POLICE SMG";
_parent._parent.rof = 4;
_parent._parent.firepower = 18;
_parent._parent.recoil = 0.8;
_parent._parent.blowback = 10;
_parent._parent.bullets = 30;
_parent._parent.idlerotate = 30;
_parent._parent.adjustrof();
_parent._parent.pushback = 3;
_parent._parent.weight = 0.9;
