shootx = 12;
shooty = -1;
handx = 40;
handy = -16;
shellX = 20;
flashX = 77;
Name = "RAPID SNIPER";
_parent._parent.rof = 15;
_parent._parent.firepower = 51;
_parent._parent.recoil = 1.2;
_parent._parent.blowback = 8;
_parent._parent.bullets = 7;
_parent._parent.idlerotate = -70;
_parent._parent.adjustrof();
_parent._parent.pushback = 15;
_parent._parent.weight = 0.8;
