shootx = 25;
shooty = 2;
handx = 30;
handy = -5;
shellX = 25;
flashX = 45;
Name = "SINE PISTOL";
_parent._parent.rof = 6;
_parent._parent.firepower = 16;
_parent._parent.recoil = 0.7;
_parent._parent.blowback = 20;
_parent._parent.bullets = 17;
_parent._parent.idlerotate = 40;
_parent._parent.adjustrof();
_parent._parent.pushback = 0;
_parent._parent.weight = 1;
