shootx = 25;
shooty = 2;
handx = 30;
handy = -5;
shellX = 25;
flashX = 45;
Name = "FIFTY EIGHT";
_parent._parent.rof = 8;
_parent._parent.firepower = 18;
_parent._parent.recoil = 1;
_parent._parent.blowback = 30;
_parent._parent.bullets = 16;
_parent._parent.idlerotate = 40;
_parent._parent.adjustrof();
_parent._parent.pushback = 0;
_parent._parent.weight = 1;
