shootx = 7;
shooty = 1;
handx = 50;
handy = -13;
shellX = 15;
flashX = 70;
Name = "CLASSIC MACHINE GUN";
_parent._parent.rof = 3;
_parent._parent.firepower = 20;
_parent._parent.recoil = 0.8;
_parent._parent.blowback = 7;
_parent._parent.bullets = 40;
_parent._parent.idlerotate = -60;
_parent._parent.adjustrof();
_parent._parent.pushback = 10;
_parent._parent.weight = 0.75;
