shootx = 7;
shooty = 0;
handx = 45;
handy = -12;
shellX = 25;
flashX = 60;
Name = "LEVER SNIPER";
_parent._parent.rof = 18;
_parent._parent.firepower = 60;
_parent._parent.recoil = 5;
_parent._parent.blowback = 10;
_parent._parent.bullets = 7;
_parent._parent.idlerotate = -80;
_parent._parent.adjustrof();
_parent._parent.pushback = 20;
_parent._parent.weight = 0.8;
